version: '3'

services:
    mssql-server:
        image: 'mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04'
        restart: always
        user: root
        environment: 
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD='AVeryStrongPassword123@!'
            - MSSQL_PID=Express
        ports:
            - 1433:1433
        volumes: 
            - mssql_data:/var/opt/mssql/data
            - mssql_logs:/var/opt/mssql/log
            - mssql_secrets:/var/opt/mssql/secrets

volumes: 
    mssql_data: {}
    mssql_logs: {}
    mssql_secrets: {}