version: '3'

services:
    mysql-server:
        image: 'mysql:8'
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        expose: 
            - "3306"
        volumes:
            - mysqldata:/var/lib/mysql
    app:
        build: 
            context: app
        ports: 
            - "85:80"
        environment: 
            - APP_NAME=lumen
            - APP_ENV=local
            - APP_KEY=
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - APP_TIMEZONE=UTC
            - LOG_CHANNEL=stack
            - LOG_SLACK_WEBHOOK_URL=
            - CACHE_DRIVER=file
            - QUEUE_CONNECTION=sync
            - DB_CONNECTION=mysql
            - DB_HOST=mysql-server
            - DB_PORT=3306
            - DB_DATABASE=test
            - DB_USERNAME=root
            - DB_PASSWORD=root
        volumes: 
            - /app/vendor
            - ./app:/app

    anp:
        build:
            context: anp
        ports:
            - "4300:4000"
        environment:
            - SERVICE_NAME=a-microservice
        volumes: 
            - /app/node_modules
            - ./anp:/app

    anp2:
        build:
            context: anp2
        environment:
            - SERVICE_NAME=a-bigger-microservice
        volumes:
            - /app/node_modules
            - ./anp2:/app
            
    rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        volumes:
          - ./rabbitmq/data/:/var/lib/rabbitmq/
          - ./rabbitmq/log/:/var/log/rabbitmq
        hostname: rabbitmq

volumes:
    rabbitmq: {}
    mysqldata: {}
